---
- import_playbook: ./tasks/create-gcp-infrastructure.yml
- import_playbook: ./tasks/setup-infrastructure.yml
- import_playbook: ./tasks/setup-domain.yml
- import_playbook: ./tasks/setup-ssl.yml
- import_playbook: ./tasks/verify-tools.yml
